export const CREATE_REVIEW_START = "CREATE_REVIEW_START";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CLEAN_UP = "CLEAN_UP";
export const UPDATE_REVIEWS_LIST = "UPDATE_REVIEWS_LIST";

export const GET_MY_REVIEW_START = "GET_MY_REVIEW_START";
export const GET_MY_REVIEW_SUCCESS = "GET_MY_REVIEW_SUCCESS";
export const GET_MY_REVIEW_FAIL = "GET_MY_REVIEW_FAIL";
