export const CREATE_REVIEW_START = "CREATE_REVIEW_START";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CLEAN_UP = "CLEAN_UP";
